# Use UpperCamelCase notation in left side (capitalize first letter of words)
#
# RECOMMENDATIONS:
# Use short codenames, persons only see visible names 
# Use all of images in same size, you can cut your images for it

[[Characters]]
CodeName = "chris" # You can use chris_happy and chris_sad, for example
VisibleName = "Chris" # Both are the same Chris, then you want to show "Chris"
Image = "chris.png"

[[Characters]]
CodeName = "exphantom_happy"
VisibleName = "Ex Phantom"
Image = "exphantom_happy.png"
